services:
 mysql_db:
  image: mysql:latest
  container_name: mysql_container
  restart: always
  environment:
   MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
   MYSQL_DATABASE: gestor_tareas
  ports:
  - "3306:3306"
  volumes:
  - mysql_data:/var/lib/mysql
  
 app:
  build: .
  container_name: gestor_tareas
  depends_on:
   - mysql_db
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/gestor_tareas
   SPRING_DATASOURCE_USERNAME: root
   SPRING_DATASOURCE_PASSWORD: ""
  ports: 
   - "8080:8080"
 
volumes:
  mysql_data:
  