services:
 mysql_db:
  image: mysql:latest
  container_name: mysql_container
  restart: always
  environment:
   MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
   MYSQL_DATABASE: gestor_tareas
  ports:
  - "3306:3306"
  volumes:
  - mysql_data:/var/lib/mysql
  
 app:
  build: .
  container_name: gestor_tareas
  depends_on:
   - mysql_db
  environment:
   DATABASE_URL: jdbc:mysql://mysqldb:3306/gestor_tareas
   DATABASE_USERNAME: root
   DATABASE_PASSWORD: ""
   DATABASE_DRIVER: spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  ports: 
   - "8080:8080"
 
volumes:
  mysql_data:
  